// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrVGFTVwO4UTsSGmEw2hUKui5yZtD3c5Q',
    appId: '1:22691156804:android:400bbf08fe1d3638993d11',
    messagingSenderId: '22691156804',
    projectId: 'ciwywt---antigravity',
    storageBucket: 'ciwywt---antigravity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFiCW4PaGtK5fXEKpU_mO5IXZghcnkaxg',
    appId: '1:22691156804:ios:277b0cc813c3472c993d11',
    messagingSenderId: '22691156804',
    projectId: 'ciwywt---antigravity',
    storageBucket: 'ciwywt---antigravity.firebasestorage.app',
    androidClientId: '22691156804-vrfnacg4f8n5980aa8rfkhnnctm3kndh.apps.googleusercontent.com',
    iosClientId: '22691156804-8e92uch7ek0i57frlkpauekmeq23v036.apps.googleusercontent.com',
    iosBundleId: 'com.ciwywt.ciwywt',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu1VLcqTJLDtP4vXDn5n6Cz4BIAXvGfj0',
    appId: '1:22691156804:web:fa19813b56c42540993d11',
    messagingSenderId: '22691156804',
    projectId: 'ciwywt---antigravity',
    authDomain: 'ciwywt---antigravity.firebaseapp.com',
    storageBucket: 'ciwywt---antigravity.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFiCW4PaGtK5fXEKpU_mO5IXZghcnkaxg',
    appId: '1:22691156804:ios:277b0cc813c3472c993d11',
    messagingSenderId: '22691156804',
    projectId: 'ciwywt---antigravity',
    storageBucket: 'ciwywt---antigravity.firebasestorage.app',
    androidClientId: '22691156804-vrfnacg4f8n5980aa8rfkhnnctm3kndh.apps.googleusercontent.com',
    iosClientId: '22691156804-8e92uch7ek0i57frlkpauekmeq23v036.apps.googleusercontent.com',
    iosBundleId: 'com.ciwywt.ciwywt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu1VLcqTJLDtP4vXDn5n6Cz4BIAXvGfj0',
    appId: '1:22691156804:web:61af71350fe1dca6993d11',
    messagingSenderId: '22691156804',
    projectId: 'ciwywt---antigravity',
    authDomain: 'ciwywt---antigravity.firebaseapp.com',
    storageBucket: 'ciwywt---antigravity.firebasestorage.app',
  );

}